language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - examples/all/node_modules
    - examples/todomvc/node_modules
    - test/manual/node_modules

jobs:
  include:
    - script: npm run test:unit
    - script: npm run test:examples
    - script: npm run test:todomvc
    - script: npm run test:manual
    - stage: github release
      script: npm run build && npm pack
      deploy:
        provider: releases
        skip_cleanup: true
        file_glob: true
        file: grammarly-focal-*.tgz
        on:
          tags: true
