language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: github release
      script: yarn build && yarn test && yarn package
      deploy:
        provider: releases
        api_key:
          secure: k+Pvk4XKUjjVjc7jJ8OVW4fjOc8dFacupYjEZ3qV8JAFPSCpLcJi0ijGHZx44r/EaaVaVMBamGCtUQR1eotq8xturxfQZz6Jug+Eu6zOUh1KqVNzqGyv4y7UfLT5HHq7bthFBmdJ7gIN0hm0Fvi0/xm7FZWoPeucnhu31WQ16dSFUw5HBMLgjDk7IaKyVslCrERwccBshxYRuwy3+Qs3kvmwu0QHGxnZmlgNdacKdgXcrdw6QfJOmAQsoidbyhIaCfxmh/ZQESCDU5WIOBjoZnEh3qZlGxvgUPUVp7bYZ68Q3g0/Xs2y5khyIKwtlCDum5E7GGUUwXtuX1WltfhWhKLtaeFN68OANI9GZTaLYWiBYsF32szkvsjB4NL8t5rsPFJ0D4zzY9WGzaBPVtE3JmwrSpPm+M2A2gbgmEzh7CT+UFIWtmNcKtQkuLVBTNnpgMBhW2XRQmVlpvMfykQuQbISsypeUqqNyIQ5br87zWIILfdGkcminSM4qtESvO/Ltd3/JxfZIv2Xdc3oq0GpB+Pl62EWGn8hnAJ0FcWX/XDTTpDLWgld26VchfQp3+T5k4ZxMyl8lSuR0okPzj+GpLkoW2hc8fqtEVcTIwU+53C/wKcPWvBbf5WTHryDLXYptjAXhOorSIybfzeVkGSbaejH7ROQBKm7n53kjy1OGv0=
        skip_cleanup: true
        file_glob: true
        file: packages/focal/grammarly-focal-*.tgz
        on:
          tags: true

notifications:
  email: false
